### ISSUE TITLE
Updated etcdadm release

### ISSUE THREAD

**Issue by mrajashree** [kubernetes-sigs/etcdadm#209]
Hi, can we get a new release for etcdadm? The latest release is about a year old and lot of changes (725 commits) have gone in since.

**Comment by dlipovetsky** [comment]
/assign

I'd like to update go to 1.16: https://github.com/kubernetes-sigs/etcdadm/pull/214, and then I'll tag v0.1.4 and release.

**Comment by dlipovetsky** [comment]
We talked about this at the last meeting. We want to use the staging build to produce artifacts, since that's a trusted build environment. I tagged v0.1.4, and the job triggered, but did not [publish artifacts](https://prow.k8s.io/log?job=etcdadm-postsubmit-push-to-staging&id=1392930550473297920). Looking into it.

**Comment by mrajashree** [comment]
closing in favor of https://github.com/kubernetes-sigs/etcdadm/releases/tag/v0.1.5
