### ISSUE TITLE
FATA[0008] [start] Error: failed to start service: exit status 1

### ISSUE THREAD

**Issue by dravenk** [kubernetes-sigs/etcdadm#249]
I tried to run it on the initialized kubeadm node and it prompts the error message described in the caption. The maintainer is expected to modify the prompt for a more detailed reason.
Here is my solution.
```
# kubeadm reset -f
# etcdadm init
```
or, maybe just skip to the next step https://github.com/kubernetes-sigs/etcdadm#adding-a-member.

**Comment by dlipovetsky** [comment]
Yes, kubeadm runs etcd as a static Pod by default. I believe the reason the etcd service fails is because the process can't listen on the default port, since the kubeadm-created etcd static Pod already listens on that port.

I'm not sure if etcdadm can give a more helpful error message, but I think etcdadm _could_ perform a preflight check to let the user know if other processes are already listening on the chosen ports.,
